package com.ashveil.guidance;

public enum GameEvent {
    PLAYER_MOVED,
    CHEST_OPENED,
    CHEST_CLOSED,
    SEED_PLANTED,
    WOOD_COLLECTED,
    CRAFTING_OPENED,
    ITEM_CRAFTED,
    PLAYER_DAMAGED,
    DUSK_STARTED,
    WHEAT_HARVESTED,
    OLD_JETTY_DISCOVERED,
    BOAT_KIT_CRAFTED,
    BOAT_BUILT,
    CRIMSON_VEIL_WARNING,
    ASHEN_RITE_REVEAL_STARTED,
    LAST_VEIL_WAVE_2_CLEARED,
    LAST_VEIL_WAVE_3_CLEARED,
    LAST_VEIL_WAVE_4_CLEARED,
    LAST_VEIL_NEAR_END,
    LAST_VEIL_COMPLETED;
}
